server:
  port: 8080


lwrs:
  db:
    account:
      driverClassName: com.mysql.jdbc.Driver
      url:
        jdbc:mysql://rm-wz953e5w684hq344jo.mysql.rds.aliyuncs.com:3306/lwrs?characterEncoding=utf-8&allowMultiQueries=true
      userName: lwrs_001
      password: Ecs567567
