server:
  port: 8080
#  port: 80

PIC_DIR:
  /home/drjr/www/pic

#wx config
WX_APP_ID:
  wxceac24c676993f3e
WX_SECRET:
  1b73554bd466efe7035af7a5f4e057cd



lwrs:
  db:
    account:
      driverClassName: com.mysql.jdbc.Driver
#      url:
          #online
#        jdbc:mysql://rm-wz953e5w684hq344j.mysql.rds.aliyuncs.com:3306/lwrs?characterEncoding=utf-8&allowMultiQueries=true
          #offline
#        jdbc:mysql://rm-wz953e5w684hq344jo.mysql.rds.aliyuncs.com:3306/lwrs?characterEncoding=utf-8&allowMultiQueries=true
#      userName: lwrs_001
#      password: Ecs567567

#      localhost
    url:
      jdbc:mysql://localhost:3306/drmain?characterEncoding=utf-8&allowMultiQueries=true
    userName: root
    password: gaibang567
